"""Add user competition relationship

Revision ID: 5e15c381821d
Revises: b564493f41d0
Create Date: 2026-10-06 15:26:34.173771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e15c381821d'
down_revision = 'b564493f41d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_competitions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], name=op.f('fk_user_competitions_competition_id_competition')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_competitions_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'competition_id', name=op.f('pk_user_competitions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_competitions')
    # ### end Alembic commands ###
