"""Models for matches

Revision ID: b564493f41d0
Revises: 0d28bb562140
Create Date: 2026-10-06 15:20:39.296656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b564493f41d0'
down_revision = '0d28bb562140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('is_top_in_country', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition')),
    sa.UniqueConstraint('api_id', name=op.f('uq_competition_api_id'))
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('api_id', name=op.f('uq_team_api_id'))
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], name=op.f('fk_match_away_team_id_team')),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], name=op.f('fk_match_competition_id_competition')),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], name=op.f('fk_match_home_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match')),
    sa.UniqueConstraint('api_id', name=op.f('uq_match_api_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('team')
    op.drop_table('competition')
    # ### end Alembic commands ###
